package cxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-07T12:02:00.926+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://cxf/", name = "WsInterface")
@XmlSeeAlso({ObjectFactory.class})
public interface WsInterface {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://cxf/WsInterface/getCatByUserRequest", output = "http://cxf/WsInterface/getCatByUserResponse")
    @RequestWrapper(localName = "getCatByUser", targetNamespace = "http://cxf/", className = "cxf.GetCatByUser")
    @WebMethod
    @ResponseWrapper(localName = "getCatByUserResponse", targetNamespace = "http://cxf/", className = "cxf.GetCatByUserResponse")
    public java.util.List<cxf.Cat> getCatByUser(
        @WebParam(name = "arg0", targetNamespace = "")
        cxf.User arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://cxf/WsInterface/helloRequest", output = "http://cxf/WsInterface/helloResponse")
    @RequestWrapper(localName = "hello", targetNamespace = "http://cxf/", className = "cxf.Hello")
    @WebMethod
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://cxf/", className = "cxf.HelloResponse")
    public java.lang.String hello(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
