package cxf.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import cxf.WsInterface;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-07T12:02:00.954+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "testws", 
                  wsdlLocation = "http://localhost:9093/ws?wsdl",
                  targetNamespace = "http://impl.cxf/") 
public class Testws extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.cxf/", "testws");
    public final static QName WsImplPort = new QName("http://impl.cxf/", "WsImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9093/ws?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Testws.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:9093/ws?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Testws(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Testws(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Testws() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Testws(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Testws(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Testws(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns WsInterface
     */
    @WebEndpoint(name = "WsImplPort")
    public WsInterface getWsImplPort() {
        return super.getPort(WsImplPort, WsInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsInterface
     */
    @WebEndpoint(name = "WsImplPort")
    public WsInterface getWsImplPort(WebServiceFeature... features) {
        return super.getPort(WsImplPort, WsInterface.class, features);
    }

}
